#----
#file:		user/makefile
#auther: 	Jason Hu
#time: 		2019/7/29
#copyright:	(C) 2018-2019 by Book OS developers. All rights reserved.
#----


#First read here
.PHONY: all

all: compile

#Compile files
compile: 
	cd lib && make
	

#Clean temporary files
clean:
	cd lib && make clean
	