#----
#file:		hal/makefile
#auther: 	Jason Hu
#time: 		2019/6/22
#copyright:	(C) 2018-2019 by Book OS developers. All rights reserved.
#----


#First read here
.PHONY: all

all: compile

#Compile files
compile: 
	cd char && make
	

#Clean temporary files
clean:
	cd char && make clean
	